### ISSUE TITLE
namespace missing

### ISSUE THREAD

**Issue by nailfor** [hzted123/yii2-amqp#1]
CronController.php

`namespace hzted123\cronjobs\controllers;
...
class CronController extends Controller ....
`
but yii2-cronjobs isn't have the "controllers" folder. If i'm write
'jobs' => [
            'class' => '\hzted123\cronjobs\controllers\CronController',

'Class hzted123\cronjobs\controllers\CronController does not exist'

but if i'm write 
'jobs' => [
            'class' => '\hzted123\cronjobs\controllers\CronController',

'Unable to find 'hzted123\cronjobs\CronController' in file: .../vendor/hzted123/yii2-cronjobs/CronController.php. Namespace missing?'

**Comment by hzted123** [comment]
fixed
